language: generic
services:
  - docker
jobs:
  include:
    - stage: build-and-test
      name: Build and Test
      script:
        - scripts/build-and-run.sh
      after_success:
        - docker-compose -f docker-micro.yml -f docker-micro-scan.yml up --abort-on-container-exit
