version: "3.9"
services:
  hawkscan:
    image: stackhawk/hawkscan:latest
    environment:
      - API_KEY=${HAWK_API_KEY}
      - APP_ID=18a430bc-e7d8-4a4d-af95-c21784b6fabe
      - APP_ENV=Travis CI
      - HOST=http://vuln-proxy:8020
    volumes:
      - .:/hawk

  vuln-proxy:
    logging:
      driver: none

  vuln-django:
    logging:
      driver: none
